# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-or-later

language: go
sudo: false
addons:
  apt:
    packages:
      - libraptor2-dev
go:
  - "1.10"

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -coverprofile=tools-golang.cov ./v0/...
  - $GOPATH/bin/goveralls -coverprofile=tools-golang.cov -service=travis-ci
